### ISSUE TITLE
failure to complete reference

### ISSUE THREAD

**Issue by niosus** [randy3k/LaTeXBox#42]
Hello @randy3k and thanks for yet another awesome plugin. Switching to it from LatexTools.

I have a problem when trying to complete a reference.

Typing `\ref{` and then <kbd>Ctrl</kbd> + <kbd>l</kbd>, <kbd>x</kbd> causes an error:
```
dispatching ref
!TEX root =  /home/igor/Papers/bogoslavskyi16pfg/bogoslavskyi16pfg.tex
Scanning file: '/home/igor/Papers/bogoslavskyi16pfg/bogoslavskyi16pfg.tex'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/home/igor/.config/sublime-text-3/Packages/LaTeXBox/latex_completion.py", line 19, in run
    self.dispatch_ref(m, point)
  File "/home/igor/.config/sublime-text-3/Packages/LaTeXBox/latex_completion.py", line 77, in dispatch_ref
    results = search_in_tex(r'\\label\{([^\{\}]+)\}', tex_root)
  File "/home/igor/.config/sublime-text-3/Packages/LaTeXBox/misc.py", line 116, in search_in_tex
    src_content = src_file.readlines()
  File "./python3.3/codecs.py", line 313, in decode
    # and return an (output, length consumed) tuple
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 2993: invalid start byte
```

I am on Sublime Text 3126 and Ubuntu 16.04 with TexLive from `apt-get` (can this be the issue?)

**Comment by randy3k** [comment]
From the message, it seems that it is caused by a non Unicode 8 character, is your bib file in UTF8?

**Comment by niosus** [comment]
Yes, you are right. This was the issue.

However, maybe there should be a warning to a user of some kind instead of silently failing?

**Comment by randy3k** [comment]
Is it really silent? :-/ at least we figured it out

Yet, I agrees that we should add some checking mechanism.
